spring:
  application:
    name: assessment-fullstack-backend

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:backend
    username: sa
    password: ''

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    locations: classpath:h2/migration
    validate-on-migrate: true

  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    de.tomreno: DEBUG

app:
  csv:
    person:
      directory: file:<project-root>/data/csv/person
  database:
    enabled: false
