CREATE TYPE color AS ENUM ('BLUE','GREEN', 'RED', 'VIOLET', 'YELLOW', 'WHITE');

CREATE TABLE person (
    id BIGINT UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    zipcode VARCHAR(5) NOT NULL,
    city VARCHAR(30) NOT NULL,
    color COLOR NOT NULL,
    CONSTRAINT person_pk PRIMARY KEY (id)
);

CREATE SEQUENCE person_seq START WITH 1 INCREMENT BY 1;
